namePrefix: local-
commonLabels:
  app: rails-docker-examples
  variant: development

bases:
  - ../../base

resources:
  - data.yaml
  - webpacker.yaml
  - postgresql.yaml
  - selenium.yaml
  - test_web.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: rails
    path: app_share.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ops-rails
    path: app_share.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: webpacker
    path: app_share.yaml

patches:
  - ingress.yaml
