namePrefix: production-
commonLabels:
  app: rails-docker-examples
  variant: production

bases:
  - ../../base

patches:
  - app.yaml
  - ingress.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: rails
    path: app_share.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ops-rails
    path: app_share.yaml
